services:
  web:
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8079:5000"
    volumes:
      - .:/app
      - db_volume:/app  # Persistencia específica para el .db (opcional, pero recomendado)
    environment:
      - APP_NAME=${APP_NAME} 
volumes:
  db_volume:  # Volumen para persistir el .db